name: Python CI

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install pytest directly (in case it's not in requirements.txt)
      - name: Install pytest directly
        run: |
          python -m pip install pytest

      # Step 5: Check pytest installation
      - name: Check pytest installation
        run: |
          python -m pip show pytest

      # Step 6: Run tests
      - name: Run tests
        run: |
          pytest
